### ISSUE TITLE
made notable closed source software

### ISSUE THREAD

**Issue by madeindjs** [fabiospampinato/ama#7]
I just wanted to have your feedback on making Notable a closed source software. I see your are an open source lover so I wonder:

- Do you think it was a good choice ?
- Did it help your project to become sustainable ?
- Did you lose sope users after this change ?

Thank you for your answers

**Comment by fabiospampinato** [comment]
Hey,

For context I think [this](https://news.ycombinator.com/item?id=23885913) is worth reading. Also I don't think I'm anywhere near "the end" so it may be kinda early to evaluate that decision properly.

> Do you think it was a good choice ?

Yes.

> Did it help your project to become sustainable ?

The project is not sustainable yet, so in some sense it didn't, though everything else being equal I possibly would have stopped justifying working on it at some point if it was open-source and just moved onto other projects. At the end of the day I need to get some money from somewhere, while Notable didn't really provide me with any yet there's still the promise of that in the future in some sense, promise which probably wouldn't be there if it was open-source and everything else was equal. It's possible that by keeping it open-source it would have instead become sustainable kinda by itself sooner, though I don't think that's likely to have happened, and it probably would have given me less freedom overall, the minute you want to move onto other things donations to you stop flowing I guess, like you have no real equity in that project.

> Did you lose sope users after this change ?

Probably, hard to quantify how much interest was lost. I'd say the success of the app will largely be a function of how good it actually is, so I'm more concentrated on that.
