### ISSUE TITLE
Uhh kinda random

### ISSUE THREAD

**Issue by vipexv** [fabiospampinato/ama#8]
What VSCode theme are you using in this picture?

![image](https://github.com/fabiospampinato/ama/assets/101529155/f38b39f3-7f26-4324-85ae-b41d7a6f428c)

**Comment by fabiospampinato** [comment]
It looks like Monokai Night https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-monokai-night

**Comment by vipexv** [comment]
Thank you mane! ❤️
